export interface ThemeItem {
  id: string;
  name: string;
  category: ThemeCategory;
  imageUrl: string;
  author: string;
  price: number;
  tags: string[];
  accentColor: string;
  downloads: number;
  description?: string; // Generated by AI later
}

export enum ThemeCategory {
  ALL = '全部',
  SAAS = 'SaaS平台',
  PORTFOLIO = '个人作品集',
  ECOMMERCE = '跨境电商',
  BLOG = '极简博客',
  DASHBOARD = '数据大屏',
  LANDING = '营销落地页',
  NFT = 'Web3/NFT',
}

export const CATEGORIES = Object.values(ThemeCategory);

export interface AiAnalysisResult {
  title: string;
  content: string;
  usageTips: string[];
}